
using System.Collections.Generic;

namespace PaPortable
{
    public class LipEntry
    {
        public string phonetic;
        public string gloss;
        public string pos;
        public string cvPat;
        public string myRef;
    }
    public class Lip3Data
    {
        public List<LipEntry> MyRecs = new List<LipEntry>();
        public Lip3Data()
        {
            MyRecs.Add(new LipEntry { phonetic = "ɱfu", gloss = "stomach (internal) [pl]", pos = "N", cvPat = "CCV", myRef = "0040p" });
            MyRecs.Add(new LipEntry { phonetic = "ɱfu", gloss = "abdomen (external) [pl]", pos = "N", cvPat = "CCV", myRef = "0039p" });
            MyRecs.Add(new LipEntry { phonetic = "ŋkɛ", gloss = "waist [pl]", pos = "N", cvPat = "CCV", myRef = "0036p" });
            MyRecs.Add(new LipEntry { phonetic = "ŋkɛ", gloss = "waist", pos = "N", cvPat = "CCV", myRef = "0036" });
            MyRecs.Add(new LipEntry { phonetic = "fjɔ̃", gloss = "suck", pos = "V", cvPat = "CCṼ", myRef = "0148" });
            MyRecs.Add(new LipEntry { phonetic = "kwɛ̃", gloss = "groan (with pain)", pos = "V", cvPat = "CCṼ", myRef = "0116" });
            MyRecs.Add(new LipEntry { phonetic = "ɲj̃ɛ̃", gloss = "palate [pl]", pos = "N", cvPat = "CC̃Ṽ", myRef = "0020p" });
            MyRecs.Add(new LipEntry { phonetic = "nsulomaʔ", gloss = "nape of neck [pl]", pos = "N", cvPat = "CCVCVCVʔ", myRef = "0024p" });
            MyRecs.Add(new LipEntry { phonetic = "nlʊaʔ", gloss = "jaw [pl]", pos = "N", cvPat = "CCVVʔ", myRef = "0021p" });
            MyRecs.Add(new LipEntry { phonetic = "mmaʔ", gloss = "back [pl]", pos = "N", cvPat = "CCVʔ", myRef = "0042p" });
            MyRecs.Add(new LipEntry { phonetic = "flɔʔ", gloss = "lip [pl]", pos = "N", cvPat = "CCVʔ", myRef = "0016p" });
            MyRecs.Add(new LipEntry { phonetic = "flɔʔ", gloss = "lip", pos = "N", cvPat = "CCVʔ", myRef = "0016" });
            MyRecs.Add(new LipEntry { phonetic = "nsuʔ", gloss = "urine [pl]", pos = "N", cvPat = "CCVʔ", myRef = "0101p" });
            MyRecs.Add(new LipEntry { phonetic = "ɲj̃ɛ̃ʔ", gloss = "mouth [pl]", pos = "N", cvPat = "CC̃Ṽʔ", myRef = "0015p" });
            MyRecs.Add(new LipEntry { phonetic = "ɲj̃ɛ̃ʔ", gloss = "lip [pl]", pos = "N", cvPat = "CC̃Ṽʔ", myRef = "0016p" });
            MyRecs.Add(new LipEntry { phonetic = "kpe", gloss = "crawl", pos = "V", cvPat = "CV", myRef = "0158" });
            MyRecs.Add(new LipEntry { phonetic = "ɡbe", gloss = "look at, watch", pos = "V", cvPat = "CV", myRef = "0133" });
            MyRecs.Add(new LipEntry { phonetic = "ɗi", gloss = "eat", pos = "V", cvPat = "CV", myRef = "0140" });
            MyRecs.Add(new LipEntry { phonetic = "tɛ", gloss = "snore", pos = "V", cvPat = "CV", myRef = "0108" });
            MyRecs.Add(new LipEntry { phonetic = "ta", gloss = "kick", pos = "V", cvPat = "CV", myRef = "0162" });
            MyRecs.Add(new LipEntry { phonetic = "to", gloss = "bridge (of nose)", pos = "N", cvPat = "CV", myRef = "0012" });
            MyRecs.Add(new LipEntry { phonetic = "to", gloss = "bridge (of nose) [pl]", pos = "N", cvPat = "CV", myRef = "0012p" });
            MyRecs.Add(new LipEntry { phonetic = "nə", gloss = "drink", pos = "V", cvPat = "CV", myRef = "0149" });
            MyRecs.Add(new LipEntry { phonetic = "nə", gloss = "bite (v)", pos = "V", cvPat = "CV", myRef = "0141" });
            MyRecs.Add(new LipEntry { phonetic = "se", gloss = "stamp (with foot)", pos = "V", cvPat = "CV", myRef = "0163" });
            MyRecs.Add(new LipEntry { phonetic = "sa", gloss = "jump (v)", pos = "V", cvPat = "CV", myRef = "0161" });
            MyRecs.Add(new LipEntry { phonetic = "sɔ", gloss = "palpitate (of heart)", pos = "V", cvPat = "CV", myRef = "0118" });
            MyRecs.Add(new LipEntry { phonetic = "jɛ", gloss = "walk", pos = "V", cvPat = "CV", myRef = "0154" });
            MyRecs.Add(new LipEntry { phonetic = "jə", gloss = "see", pos = "V", cvPat = "CV", myRef = "0131" });
            MyRecs.Add(new LipEntry { phonetic = "ke", gloss = "swim", pos = "V", cvPat = "CV", myRef = "0160" });
            MyRecs.Add(new LipEntry { phonetic = "nɔ̃", gloss = "hear", pos = "V", cvPat = "CṼ", myRef = "0134" });
            MyRecs.Add(new LipEntry { phonetic = "mʌŋkle", gloss = "step (v)", pos = "V", cvPat = "CVCCCV", myRef = "0155" });
            MyRecs.Add(new LipEntry { phonetic = "fiŋkə", gloss = "hiccough (n)", cvPat = "CVCCV", myRef = "0114" });
            MyRecs.Add(new LipEntry { phonetic = "tiŋɡə", gloss = "shiver, tremble", pos = "V", cvPat = "CVCCV", myRef = "0122" });
            MyRecs.Add(new LipEntry { phonetic = "kakwɛ", gloss = "throat [pl]", pos = "N", cvPat = "CVCCV", myRef = "0025p" });
            MyRecs.Add(new LipEntry { phonetic = "kəkwə", gloss = "umbilical cord [pl]", pos = "N", cvPat = "CVCCV", myRef = "0038p" });
            MyRecs.Add(new LipEntry { phonetic = "lɛkwɛnlolobiʔ", gloss = "voice box, larynx, Adam’s apple", pos = "N", cvPat = "CVCCVCCVCVCVʔ", myRef = "0026" });
            MyRecs.Add(new LipEntry { phonetic = "kakwɛnlolobiʔ", gloss = "voice box, larynx, Adam’s apple [pl]", pos = "N", cvPat = "CVCCVCCVCVCVʔ", myRef = "0026p" });
            MyRecs.Add(new LipEntry { phonetic = "kɛmjatokatoʔ", gloss = "palate", pos = "N", cvPat = "CVCCVCVCVCVʔ", myRef = "0020" });
            MyRecs.Add(new LipEntry { phonetic = "kɛmjatokatoʔ", gloss = "palate [pl]", pos = "N", cvPat = "CVCCVCVCVCVʔ", myRef = "0020p" });
            MyRecs.Add(new LipEntry { phonetic = "kadjakamiʔ", gloss = "tongue [pl]", pos = "N", cvPat = "CVCCVCVCVʔ", myRef = "0017p" });
            MyRecs.Add(new LipEntry { phonetic = "səndeʔ", gloss = "molar tooth [pl]", pos = "N", cvPat = "CVCCVʔ", myRef = "0019p" });
            MyRecs.Add(new LipEntry { phonetic = "səndeʔ", gloss = "molar tooth", pos = "N", cvPat = "CVCCVʔ", myRef = "0019" });
            MyRecs.Add(new LipEntry { phonetic = "mɪnɪ", gloss = "swallow", pos = "V", cvPat = "CVCV", myRef = "0145" });
            MyRecs.Add(new LipEntry { phonetic = "tidi", gloss = "touch, feel (active)", pos = "V", cvPat = "CVCV", myRef = "0138" });
            MyRecs.Add(new LipEntry { phonetic = "tufə", gloss = "spit", pos = "V", cvPat = "CVCV", myRef = "0111" });
            MyRecs.Add(new LipEntry { phonetic = "disi", gloss = "head", pos = "N", cvPat = "CVCV", myRef = "0003" });
            MyRecs.Add(new LipEntry { phonetic = "tʃetʃi", gloss = "run", pos = "V", cvPat = "CVCV", myRef = "0159" });
            MyRecs.Add(new LipEntry { phonetic = "jɪmɪ", gloss = "crunch", pos = "V", cvPat = "CVCV", myRef = "0142" });
            MyRecs.Add(new LipEntry { phonetic = "kekpi", gloss = "beard [pl]", pos = "N", cvPat = "CVCV", myRef = "0028p" });
            MyRecs.Add(new LipEntry { phonetic = "kafu", gloss = "abdomen (external)", pos = "N", cvPat = "CVCV", myRef = "0039" });
            MyRecs.Add(new LipEntry { phonetic = "kafu", gloss = "stomach (internal)", pos = "N", cvPat = "CVCV", myRef = "0040" });
            MyRecs.Add(new LipEntry { phonetic = "kutʃə", gloss = "side (of body)", pos = "N", cvPat = "CVCV", myRef = "0035" });
            MyRecs.Add(new LipEntry { phonetic = "kɔsɪ", gloss = "cough (v)", pos = "V", cvPat = "CVCV", myRef = "0112" });
            MyRecs.Add(new LipEntry { phonetic = "wula", gloss = "yawn", pos = "V", cvPat = "CVCV", myRef = "0107" });
            MyRecs.Add(new LipEntry { phonetic = "wɔnɔ", gloss = "breathe", pos = "V", cvPat = "CVCV", myRef = "0106" });
            MyRecs.Add(new LipEntry { phonetic = "bɛkɔ̃", gloss = "navel [pl]", pos = "N", cvPat = "CVCṼ", myRef = "0037p" });
            MyRecs.Add(new LipEntry { phonetic = "sɛkɔ̃", gloss = "navel", pos = "N", cvPat = "CVCṼ", myRef = "0037" });
            MyRecs.Add(new LipEntry { phonetic = "kɛj̃ɛ̃", gloss = "palate", pos = "N", cvPat = "CVC̃Ṽ", myRef = "0020" });
            MyRecs.Add(new LipEntry { phonetic = "lɛ̃j̃i", gloss = "molar tooth", pos = "N", cvPat = "CṼC̃V", myRef = "0019" });
            MyRecs.Add(new LipEntry { phonetic = "lɛ̃w̃ɔ̃", gloss = "bridge (of nose)", pos = "N", cvPat = "CṼC̃Ṽ", myRef = "0012" });
            MyRecs.Add(new LipEntry { phonetic = "lɛ̃w̃ɔ̃", gloss = "nose", pos = "N", cvPat = "CṼC̃Ṽ", myRef = "0011" });
            MyRecs.Add(new LipEntry { phonetic = "wĩj̃ã", gloss = "wave (hand as a greeting) (v)", pos = "V", cvPat = "CṼC̃Ṽ", myRef = "0165" });
            MyRecs.Add(new LipEntry { phonetic = "binansə", gloss = "eyelash [pl]", pos = "N", cvPat = "CVCVCCV", myRef = "0009p" });
            MyRecs.Add(new LipEntry { phonetic = "ditiŋke", gloss = "buttock", pos = "N", cvPat = "CVCVCCV", myRef = "0044" });
            MyRecs.Add(new LipEntry { phonetic = "kʌnansə", gloss = "eyebrow", pos = "N", cvPat = "CVCVCCV", myRef = "0007" });
            MyRecs.Add(new LipEntry { phonetic = "ɡɨnansə", gloss = "eyebrow [pl]", pos = "N", cvPat = "CVCVCCV", myRef = "0007p" });
            MyRecs.Add(new LipEntry { phonetic = "dinambɛʔ", gloss = "pupil (of eye)", pos = "N", cvPat = "CVCVCCVʔ", myRef = "0010" });
            MyRecs.Add(new LipEntry { phonetic = "kpësïkpi", gloss = "faint", pos = "V", cvPat = "CVCVCV", myRef = "0127" });
            MyRecs.Add(new LipEntry { phonetic = "kpakpakpa", gloss = "shiver, tremble", pos = "V", cvPat = "CVCVCV", myRef = "0122" });
            MyRecs.Add(new LipEntry { phonetic = "buteko", gloss = "stumble", pos = "V", cvPat = "CVCVCV", myRef = "0156" });
            MyRecs.Add(new LipEntry { phonetic = "sɛkɔto", gloss = "umbilical cord [pl]", pos = "N", cvPat = "CVCVCV", myRef = "0038p" });
            MyRecs.Add(new LipEntry { phonetic = "sɛkɔto", gloss = "umbilical cord", pos = "N", cvPat = "CVCVCV", myRef = "0038" });
            MyRecs.Add(new LipEntry { phonetic = "tʃɛkɛlɛ", gloss = "limp", pos = "V", cvPat = "CVCVCV", myRef = "0157" });
            MyRecs.Add(new LipEntry { phonetic = "tʃokoto", gloss = "listen", pos = "V", cvPat = "CVCVCV", myRef = "0135" });
            MyRecs.Add(new LipEntry { phonetic = "sɔnĭto", gloss = "tuft, lock (of hair) [pl]", pos = "N", cvPat = "CVCV̆CV", myRef = "0030p" });
            MyRecs.Add(new LipEntry { phonetic = "sɔnĭto", gloss = "tuft, lock (of hair)", pos = "N", cvPat = "CVCV̆CV", myRef = "0030" });
            MyRecs.Add(new LipEntry { phonetic = "bebikasiakɔʔ", gloss = "womb [pl]", pos = "N", cvPat = "CVCVCVCVVCVʔ", myRef = "0041p" });
            MyRecs.Add(new LipEntry { phonetic = "lɛmɔkɔsiʔ", gloss = "shoulder", pos = "N", cvPat = "CVCVCVCVʔ", myRef = "0031" });
            MyRecs.Add(new LipEntry { phonetic = "lɛmɔkɔsiʔ", gloss = "shoulder blade", pos = "N", cvPat = "CVCVCVCVʔ", myRef = "0032" });
            MyRecs.Add(new LipEntry { phonetic = "lɛkɔsibiʔ", gloss = "chest", pos = "N", cvPat = "CVCVCVCVʔ", myRef = "0033" });
            MyRecs.Add(new LipEntry { phonetic = "kasulomaʔ", gloss = "nape of neck", pos = "N", cvPat = "CVCVCVCVʔ", myRef = "0024" });
            MyRecs.Add(new LipEntry { phonetic = "sikpĭlibiʔ", gloss = "chin", pos = "N", cvPat = "CVCV̆CVCVʔ", myRef = "0022" });
            MyRecs.Add(new LipEntry { phonetic = "dinamiʔ", gloss = "eye", pos = "N", cvPat = "CVCVCVʔ", myRef = "0006" });
            MyRecs.Add(new LipEntry { phonetic = "letumɛʔ", gloss = "forehead", pos = "N", cvPat = "CVCVCVʔ", myRef = "0004" });
            MyRecs.Add(new LipEntry { phonetic = "koto-siʔ", gloss = "cheek", pos = "N", cvPat = "CVCV-CVʔ", myRef = "0014" });
            MyRecs.Add(new LipEntry { phonetic = "sɛw̃ɔ̃niʔ", gloss = "hair (of head) [pl]", pos = "N", cvPat = "CVC̃ṼCVʔ", myRef = "0027p" });
            MyRecs.Add(new LipEntry { phonetic = "kukuə", gloss = "skin (of man)", pos = "N", cvPat = "CVCVV", myRef = "0002" });
            MyRecs.Add(new LipEntry { phonetic = "bimuʌʔ", gloss = "neck [pl]", pos = "N", cvPat = "CVCVVʔ", myRef = "0023p" });
            MyRecs.Add(new LipEntry { phonetic = "simuʌʔ", gloss = "neck", pos = "N", cvPat = "CVCVVʔ", myRef = "0023" });
            MyRecs.Add(new LipEntry { phonetic = "kɛmi̯ɛʔ", gloss = "stomach (internal)", pos = "N", cvPat = "CVCVVʔ", myRef = "0040" });
            MyRecs.Add(new LipEntry { phonetic = "kɛmi̯ɛʔ", gloss = "stomach (internal) [pl]", pos = "N", cvPat = "CVCVVʔ", myRef = "0040p" });
            MyRecs.Add(new LipEntry { phonetic = "kalʊaʔ", gloss = "jaw", pos = "N", cvPat = "CVCVVʔ", myRef = "0021" });
            MyRecs.Add(new LipEntry { phonetic = "kamaʔ", gloss = "back", pos = "N", cvPat = "CVCVʔ", myRef = "0042" });
            MyRecs.Add(new LipEntry { phonetic = "kateʔ", gloss = "bridge (of nose) [pl]", pos = "N", cvPat = "CVCVʔ", myRef = "0012p" });
            MyRecs.Add(new LipEntry { phonetic = "kəsuʔ", gloss = "urine", pos = "N", cvPat = "CVCVʔ", myRef = "0101" });
            MyRecs.Add(new LipEntry { phonetic = "kobiʔ", gloss = "shoulder blade [pl]", pos = "N", cvPat = "CVCVʔ", myRef = "0032p" });
            MyRecs.Add(new LipEntry { phonetic = "kobiʔ", gloss = "shoulder blade", pos = "N", cvPat = "CVCVʔ", myRef = "0032" });
            MyRecs.Add(new LipEntry { phonetic = "kotoʔ", gloss = "ear", pos = "N", cvPat = "CVCVʔ", myRef = "0013" });
            MyRecs.Add(new LipEntry { phonetic = "lɛmɪ̃ʔ", gloss = "breast", pos = "N", cvPat = "CVCṼʔ", myRef = "0034" });
            MyRecs.Add(new LipEntry { phonetic = "kɛj̃ɛ̃ʔ", gloss = "lip", pos = "N", cvPat = "CVC̃Ṽʔ", myRef = "0016" });
            MyRecs.Add(new LipEntry { phonetic = "kɛj̃ɛ̃ʔ", gloss = "mouth", pos = "N", cvPat = "CVC̃Ṽʔ", myRef = "0015" });
            MyRecs.Add(new LipEntry { phonetic = "lɛ̃j̃ĩʔ", gloss = "tooth", pos = "N", cvPat = "CṼC̃Ṽʔ", myRef = "0018" });
            MyRecs.Add(new LipEntry { phonetic = "siʌ", gloss = "sit", pos = "V", cvPat = "CVV", myRef = "0150" });
            MyRecs.Add(new LipEntry { phonetic = "diad̪e", gloss = "taste", pos = "V", cvPat = "CVVCV", myRef = "0139" });
            MyRecs.Add(new LipEntry { phonetic = "jaanɔ", gloss = "smell (v)", pos = "V", cvPat = "CVVCV", myRef = "0136" });
            MyRecs.Add(new LipEntry { phonetic = "ukwə", gloss = "umbilical cord", pos = "N", cvPat = "VCCV", myRef = "0038" });
            MyRecs.Add(new LipEntry { phonetic = "ɔkwɛ", gloss = "throat", pos = "N", cvPat = "VCCV", myRef = "0025" });
            MyRecs.Add(new LipEntry { phonetic = "ɛswatobisə", gloss = "hair (of body) [pl]", pos = "N", cvPat = "VCCVCVCVCV", myRef = "0029p" });
            MyRecs.Add(new LipEntry { phonetic = "ɛswatobisə", gloss = "hair (of body)", pos = "N", cvPat = "VCCVCVCVCV", myRef = "0029" });
            MyRecs.Add(new LipEntry { phonetic = "odjakamiʔ", gloss = "tongue", pos = "N", cvPat = "VCCVCVCVʔ", myRef = "0017" });
            MyRecs.Add(new LipEntry { phonetic = "ifə", gloss = "blow (with mouth)", cvPat = "VCV", myRef = "0110" });
            MyRecs.Add(new LipEntry { phonetic = "esi", gloss = "head [pl]", pos = "N", cvPat = "VCV", myRef = "0003p" });
            MyRecs.Add(new LipEntry { phonetic = "etʃə", gloss = "side (of body) [pl]", pos = "N", cvPat = "VCV", myRef = "0035p" });
            MyRecs.Add(new LipEntry { phonetic = "ɛtu", gloss = "skin (of man) [pl]", pos = "N", cvPat = "VCV", myRef = "0002p" });
            MyRecs.Add(new LipEntry { phonetic = "ɛtu", gloss = "skin (of man)", pos = "N", cvPat = "VCV", myRef = "0002" });
            MyRecs.Add(new LipEntry { phonetic = "ukpi", gloss = "beard", pos = "N", cvPat = "VCV", myRef = "0028" });
            MyRecs.Add(new LipEntry { phonetic = "ɔkɔ", gloss = "cough (v)", pos = "V", cvPat = "VCV", myRef = "0112" });
            MyRecs.Add(new LipEntry { phonetic = "ãj̃i", gloss = "molar tooth [pl]", pos = "N", cvPat = "ṼC̃V", myRef = "0019p" });
            MyRecs.Add(new LipEntry { phonetic = "ãw̃ɔ̃", gloss = "bridge (of nose) [pl]", pos = "N", cvPat = "ṼC̃Ṽ", myRef = "0012p" });
            MyRecs.Add(new LipEntry { phonetic = "ãw̃ɔ̃", gloss = "nose [pl]", pos = "N", cvPat = "ṼC̃Ṽ", myRef = "0011p" });
            MyRecs.Add(new LipEntry { phonetic = "etiŋke", gloss = "buttock [pl]", pos = "N", cvPat = "VCVCCV", myRef = "0044p" });
            MyRecs.Add(new LipEntry { phonetic = "onansə", gloss = "eyelash", pos = "N", cvPat = "VCVCCV", myRef = "0009" });
            MyRecs.Add(new LipEntry { phonetic = "ekelbiʔ", gloss = "tuft, lock (of hair)", pos = "N", cvPat = "VCVCCVʔ", myRef = "0030" });
            MyRecs.Add(new LipEntry { phonetic = "ɛnambɛʔ", gloss = "pupil (of eye) [pl]", pos = "N", cvPat = "VCVCCVʔ", myRef = "0010p" });
            MyRecs.Add(new LipEntry { phonetic = "akelbiʔ", gloss = "tuft, lock (of hair) [pl]", pos = "N", cvPat = "VCVCCVʔ", myRef = "0030p" });
            MyRecs.Add(new LipEntry { phonetic = "asɔto", gloss = "side (of body) [pl]", pos = "N", cvPat = "VCVCV", myRef = "0035p" });
            MyRecs.Add(new LipEntry { phonetic = "asɔto", gloss = "side (of body)", pos = "N", cvPat = "VCVCV", myRef = "0035" });
            MyRecs.Add(new LipEntry { phonetic = "akɔnɔnɔ", gloss = "snore", pos = "V", cvPat = "VCVCVCV", myRef = "0108" });
            MyRecs.Add(new LipEntry { phonetic = "ɛnamitukatoʔ", gloss = "eyelid", pos = "N", cvPat = "VCVCVCVCVCVʔ", myRef = "0008" });
            MyRecs.Add(new LipEntry { phonetic = "ɛnamitukatoʔ", gloss = "eyelid [pl]", pos = "N", cvPat = "VCVCVCVCVCVʔ", myRef = "0008p" });
            MyRecs.Add(new LipEntry { phonetic = "obikasiakɔʔ", gloss = "womb", pos = "N", cvPat = "VCVCVCVVCVʔ", myRef = "0041" });
            MyRecs.Add(new LipEntry { phonetic = "amɔkɔsiʔ", gloss = "shoulder [pl]", pos = "N", cvPat = "VCVCVCVʔ", myRef = "0031p" });
            MyRecs.Add(new LipEntry { phonetic = "amɔkɔsiʔ", gloss = "shoulder blade [pl]", pos = "N", cvPat = "VCVCVCVʔ", myRef = "0032p" });
            MyRecs.Add(new LipEntry { phonetic = "akɔsibiʔ", gloss = "chest [pl]", pos = "N", cvPat = "VCVCVCVʔ", myRef = "0033p" });
            MyRecs.Add(new LipEntry { phonetic = "ekpĭlibiʔ", gloss = "chin [pl]", pos = "N", cvPat = "VCV̆CVCVʔ", myRef = "0022p" });
            MyRecs.Add(new LipEntry { phonetic = "atumɛʔ", gloss = "forehead [pl]", pos = "N", cvPat = "VCVCVʔ", myRef = "0004p" });
            MyRecs.Add(new LipEntry { phonetic = "anamiʔ", gloss = "face [pl]", pos = "N", cvPat = "VCVCVʔ", myRef = "0005p" });
            MyRecs.Add(new LipEntry { phonetic = "anamiʔ", gloss = "face", pos = "N", cvPat = "VCVCVʔ", myRef = "0005" });
            MyRecs.Add(new LipEntry { phonetic = "anamiʔ", gloss = "eye [pl]", pos = "N", cvPat = "VCVCVʔ", myRef = "0006p" });
            MyRecs.Add(new LipEntry { phonetic = "ato-siʔ", gloss = "cheek [pl]", pos = "N", cvPat = "VCV-CVʔ", myRef = "0014p" });
            MyRecs.Add(new LipEntry { phonetic = "ɔw̃ɔ̃niʔ", gloss = "hair (of head)", pos = "N", cvPat = "VC̃ṼCVʔ", myRef = "0027" });
            MyRecs.Add(new LipEntry { phonetic = "ɛkuə", gloss = "skin (of man) [pl]", pos = "N", cvPat = "VCVV", myRef = "0002p" });
            MyRecs.Add(new LipEntry { phonetic = "ĩsi̯ə", gloss = "sneeze (v)", cvPat = "ṼCVV", myRef = "0115" });
            MyRecs.Add(new LipEntry { phonetic = "ofiabi̯e", gloss = "blow (with mouth)", cvPat = "VCVVCVV", myRef = "0110" });
            MyRecs.Add(new LipEntry { phonetic = "asuaʔ", gloss = "skin (of man)", pos = "N", cvPat = "VCVVʔ", myRef = "0002" });
            MyRecs.Add(new LipEntry { phonetic = "asuaʔ", gloss = "skin (of man) [pl]", pos = "N", cvPat = "VCVVʔ", myRef = "0002p" });
            MyRecs.Add(new LipEntry { phonetic = "asuaʔ", gloss = "body [pl]", pos = "N", cvPat = "VCVVʔ", myRef = "0001p" });
            MyRecs.Add(new LipEntry { phonetic = "asuaʔ", gloss = "body", pos = "N", cvPat = "VCVVʔ", myRef = "0001" });
            MyRecs.Add(new LipEntry { phonetic = "atoʔ", gloss = "ear [pl]", pos = "N", cvPat = "VCVʔ", myRef = "0013p" });
            MyRecs.Add(new LipEntry { phonetic = "oteʔ", gloss = "bridge (of nose)", pos = "N", cvPat = "VCVʔ", myRef = "0012" });
            MyRecs.Add(new LipEntry { phonetic = "amɪ̃ʔ", gloss = "breast [pl]", pos = "N", cvPat = "VCṼʔ", myRef = "0034p" });
            MyRecs.Add(new LipEntry { phonetic = "ãj̃ĩʔ", gloss = "tooth [pl]", pos = "N", cvPat = "ṼC̃Ṽʔ", myRef = "0018p" });
        }
    }
}
